# Generated by Django 4.2.19 on 2025-04-27 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่งซื้อ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ยอดรวม')),
                ('status', models.CharField(choices=[('pending', 'รอการยืนยัน'), ('processing', 'กำลังดำเนินการ'), ('shipping', 'กำลังจัดส่ง'), ('delivered', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=50, verbose_name='สถานะการจัดส่ง')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งซื้อ')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='จำนวน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food.order')),
            ],
            options={
                'verbose_name': 'รายการสั่งซื้อ',
                'verbose_name_plural': 'รายการสั่งซื้อ',
            },
        ),
    ]
